[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"

[env]
  NEXT_PUBLIC_SUPABASE_URL = "https://demo.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "demo-anon-key"
  NEXT_PUBLIC_STRIPE_PK = "pk_test_demo"